apiVersion: v1
kind: Pod # smallest unit, similar function, tight integration between containers
metadata:
  name: client-pod
  labels:
    component: web  # name arbitrary
spec:
  containers:
    - name: client
      image: stephengrider/multi-worker
      ports:
        - containerPort: 9999